### ISSUE TITLE
Socket is not bound

### ISSUE THREAD

**Issue by samaneh-kamalian** [Incrementing/react-native-ntp-sync#1] opened 2021-03-01 16:59 UTC
Hi.
Sometimes can get time from servers, but most of time return this error: Socket is not bound
I test lots of port instead of 0 but result is same!

**Comment by incrementing** [comment] 2021-03-01 19:50
Can you post the NTP servers and ports you're trying to use?

**Comment by luneo7** [comment] 2021-03-01 22:28
The problem is that we are trying to use the send function not using the bind callback or the `listening` event: I fixed that in my fork: https://github.com/luneo7/react-native-ntp-sync/blob/master/src/client.ts#L88

**Comment by samaneh-kamalian** [comment] 2021-03-02 06:03
> The problem is that we are trying to use the send function not using the bind callback or the `listening` event: I fixed that in my fork: https://github.com/luneo7/react-native-ntp-sync/blob/master/src/client.ts#L88

Thanks a lot for your reply. 
I want to use your fork with this command: `npm install luneo7/react-native-ntp-sync`
but in bundle, I have this error:
`However, this package itself specifies a main module field that could not be resolved (/node_modules/@luneo7/react-native-ntp-sync/dist/index.js. Indeed, none of these files exist:`

**Comment by samaneh-kamalian** [comment] 2021-03-02 06:37
> Can you post the NTP servers and ports you're trying to use?


  this.ntpServers = [
    { server: "time.cloudflare.com", port: 123 },
    { server: "time.google.com", port: 123 },
    { server: "0.pool.ntp.org", port: 123 },
    { server: "1.pool.ntp.org", port: 123 },
  ];

These are the ones used by the library itself

**Comment by samaneh-kamalian** [comment] 2021-03-02 07:45
> The problem is that we are trying to use the send function not using the bind callback or the `listening` event: I fixed that in my fork: https://github.com/luneo7/react-native-ntp-sync/blob/master/src/client.ts#L88

I changed the code like you and my problem was solved.
Thank you

**Comment by luneo7** [comment] 2021-03-02 20:43
> > The problem is that we are trying to use the send function not using the bind callback or the `listening` event: I fixed that in my fork: https://github.com/luneo7/react-native-ntp-sync/blob/master/src/client.ts#L88
> 
> Thanks a lot for your reply.
> I want to use your fork with this command: `npm install luneo7/react-native-ntp-sync`
> but in bundle, I have this error:
> `However, this package itself specifies a main module field that could not be resolved (/node_modules/@luneo7/react-native-ntp-sync/dist/index.js. Indeed, none of these files exist:`

Can you post the full error? this is not happening for me =/

**Comment by incrementing** [comment] 2021-03-03 19:45
> > The problem is that we are trying to use the send function not using the bind callback or the `listening` event: I fixed that in my fork: https://github.com/luneo7/react-native-ntp-sync/blob/master/src/client.ts#L88
> 
> I changed the code like you and my problem was solved.
> Thank you

Merged your [pull request](https://github.com/Incrementing/react-native-ntp-sync/pull/2) .

**Closed as completed by incrementing** 2021-03-03 19:45 UTC
